package com.dfeer.plugin.database

import com.dfeer.plugin.model.ColumnInfo
import com.dfeer.plugin.model.TableInfo
import com.intellij.database.model.ObjectKind
import com.intellij.database.psi.DbColumn
import com.intellij.database.psi.DbDataSource
import com.intellij.database.psi.DbTable
import com.intellij.database.util.DasUtil

class DatabaseReader() {

    fun listTables(dataSource: DbDataSource): List<DbTable> {
        val tables = mutableListOf<DbTable>()
        dataSource.model.modelRoots.forEach { schema ->
            schema.getDasChildren(ObjectKind.TABLE).forEach { obj ->
                if (obj is DbTable) {
                    tables.add(obj)
                }
            }
            schema.getDasChildren(ObjectKind.VIEW).forEach { obj ->
                if (obj is DbTable) {
                    tables.add(obj)
                }
            }
        }
        return tables
    }

    fun readTableInfo(table: DbTable): TableInfo {
        val columns = mutableListOf<ColumnInfo>()
        table.getDasChildren(ObjectKind.COLUMN).forEach { obj ->
            if (obj is DbColumn) {
                columns.add(readColumnInfo(obj))
            }
        }
        return TableInfo(
            name = table.name, comment = table.comment ?: "", columns = columns
        )
    }

    private fun readColumnInfo(col: DbColumn): ColumnInfo {
        val typeSpec = col.dasType.specification
        return ColumnInfo(
            name = col.name,
            type = typeSpec,
            comment = col.comment ?: "",
            isPrimaryKey = DasUtil.isPrimary(col),
            isAutoIncrement = DasUtil.isAutoGenerated(col),
            nullable = !col.isNotNull
        )
    }
}
